/*
The MIT License

Copyright (c) 2016-2023 kong <congcoi123@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

package com.tenio.core.bootstrap;

import com.tenio.core.bootstrap.annotation.Autowired;
import com.tenio.core.bootstrap.annotation.Component;
import com.tenio.core.bootstrap.configuration.ConfigurationHandler;
import com.tenio.core.bootstrap.injector.BeanClass;
import com.tenio.core.bootstrap.injector.Injector;
import com.tenio.core.command.client.ClientCommandManager;
import com.tenio.core.command.system.SystemCommandManager;
import com.tenio.core.event.handler.EventHandler;
import jakarta.servlet.http.HttpServlet;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * This class provides instances for the events handler and the configuration setups.
 */
@Component
public final class BootstrapHandler {

  @Autowired
  private EventHandler eventHandler;

  @Autowired
  private ConfigurationHandler configurationHandler;

  private SystemCommandManager systemCommandManager;
  private ClientCommandManager clientCommandManager;
  private Map<Class<?>, Class<?>> reversedClassesMap;
  private Map<BeanClass, Object> classBeansMap;
  private Map<String, HttpServlet> servletMap;

  /**
   * Retrieves an events handler.
   *
   * @return the {@link EventHandler} instance
   */
  public EventHandler getEventHandler() {
    return eventHandler;
  }

  /**
   * Retrieves a system commands' manager.
   *
   * @return the {@link SystemCommandManager} instance
   * @since 0.4.0
   */
  public SystemCommandManager getSystemCommandManager() {
    return systemCommandManager;
  }

  /**
   * Sets the system command manager.
   *
   * @param systemCommandManager an instance of {@link SystemCommandManager}
   */
  public void setSystemCommandManager(SystemCommandManager systemCommandManager) {
    this.systemCommandManager = systemCommandManager;
  }

  /**
   * Retrieves a client commands' manager.
   *
   * @return the {@link ClientCommandManager} instance
   * @since 0.5.0
   */
  public ClientCommandManager getClientCommandManager() {
    return clientCommandManager;
  }

  /**
   * Sets the client command manager.
   *
   * @param clientCommandManager an instance of {@link ClientCommandManager}
   */
  public void setClientCommandManager(ClientCommandManager clientCommandManager) {
    this.clientCommandManager = clientCommandManager;
  }

  /**
   * Retrieves a configuration setups.
   *
   * @return the {@link ConfigurationHandler} instance
   */
  public ConfigurationHandler getConfigurationHandler() {
    return configurationHandler;
  }

  /**
   * Creates mapping classes from {@link Injector} which should have reversed keys and values.
   * NOTE: This will override duplicated implemented classes and only keep one.
   *
   * @param classesMap a map of classes
   */
  public void createReversedClassesMap(Map<Class<?>, Class<?>> classesMap) {
    reversedClassesMap = new HashMap<>();
    classesMap.forEach((key, value) -> reversedClassesMap.put(value, key));
  }

  /**
   * Sets all beans generated by {@link Injector}.
   *
   * @param classBeansMap a map of beans
   */
  public void setClassBeansMap(Map<BeanClass, Object> classBeansMap) {
    this.classBeansMap = classBeansMap;
  }

  /**
   * Gets bean by class.
   *
   * @param clazz the type of bean
   * @param name name of bean
   * @return an instance of class if available, otherwise returns {@code null}
   * @param <T> cast type
   */
  public <T> T getBeanByClazz(Class<T> clazz, String name) {
    // We check its interface by looking at the reversed mapping classes
    var implementedClazz = reversedClassesMap.get(clazz);
    if (Objects.isNull(implementedClazz)) {
      return null;
    }
    var object = classBeansMap.get(new BeanClass(implementedClazz, name));
    return Objects.isNull(object) ? null : clazz.isInstance(object) ? clazz.cast(object) : null;
  }

  /**
   * Gets bean by class.
   *
   * @param clazz the type of bean
   * @return an instance of class if available, otherwise returns {@code null}
   * @param <T> cast type
   */
  public <T> T getBeanByClazz(Class<T> clazz) {
    return getBeanByClazz(clazz, "");
  }

  /**
   * Retrieves servlet configuration.
   *
   * @return a {@link Map} of servlet configuration
   */
  public Map<String, HttpServlet> getServletMap() {
    return servletMap;
  }

  /**
   * Sets servlet configuration.
   *
   * @param servletMap a {@link Map} of servlet configurations
   */
  public void setServletMap(Map<String, HttpServlet> servletMap) {
    this.servletMap = servletMap;
  }
}
