# @author: kong<congcoi123@gmail.com>

version: '3'

networks:
  common:
    driver: bridge

services:
  sample_web:
    container_name: sample_web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    #tty: true
    #restart: always
    depends_on:
      - sample_app
    links:
      - sample_app
    ports:
      - '${WEB_PORT}:80'
      - '${WEB_SSL_PORT}:443'
    volumes:
      # The reference setting directories
      - ./docker/web/conf:/etc/nginx
      # The reference folders
      - ./sample-app:/var/www/sample-app
      # The reference logs
      - ./docker/gen/logs/nginx:/var/log/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - common

  sample_app:
    container_name: sample_app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    #tty: true
    #restart: always
    depends_on:
      - sample_db
    ports:
      - '${FPM_PORT}:9000'
    volumes:
      # The reference setting directories
      - ./docker/app/conf/php.ini:/etc/php.ini
      - ./docker/app/conf/www.conf:/etc/php-fpm.d/www.conf
      # The reference folders
      - ./sample-app:/var/www/sample-app
      # The reference logs
      - ./docker/gen/logs/php-fpm:/var/log/php-fpm
      - ./docker/gen/logs/xhprof:/var/log/xhprof
      # tmp
      - ./docker/gen/tmp:/tmp
    networks:
      - common

  sample_db:
    container_name: sample_db
    image: mysql:5.5.62
    command: mysqld --user=root
    #restart: always
    #tty: true
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      # The reference setting directories
      - ./docker/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/script:/docker
      # The folders for dump files and migration files
      - ./docker/db/dump:/dump
      - ./sample-app/migrations:/migrations
      ################# Setting #################
      # If you get an error when connecting, delete this data folder
      # When this data folder exists, the following entry points are not implemented
      # (that means all files are imported for only the first time)
      # Delete this data folder if you want to import all your desired files from the beginning
      - ./docker/gen/data:/var/lib/mysql
      - ./docker/gen/logs/mysql:/var/log/mysql
      ################# Entry point #################
      # All scripts are implemented from this folder (in the Alphabet order)
      # Trick: The recommended script name is [1_ <first_action> .sh, 2_ <second_action> .sh, ...]
      - ./docker/db/script:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - common

  sample_cache:
    container_name: sample_cache
    image: redis
    #restart: always
    #tty: true
    ports:
      - '6379:6379'
    volumes:
      # The reference folders
      - ./docker/gen/cache:/data
      # The reference logs
      - ./docker/gen/logs/redis:/var/log/redis
    networks:
      - common
