package com.tenio.entitas.utils;

import com.tenio.engine.entitas.Entity;
import com.tenio.entitas.components.Interactive;
import com.tenio.entitas.components.Player;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2Entity extends Entity {

    public Interactive InteractiveComponent = new Interactive();
    public Player PlayerComponent = new Player();

    public Test2Entity() {
    	
    }

    public boolean isInteractive() {
        return hasComponent(TestComponentIds.Interactive);
    }

    public Test2Entity setInteractive(boolean value) {
        if (value != hasComponent(TestComponentIds.Interactive)) {
            if (value) {
                addComponent(TestComponentIds.Interactive, InteractiveComponent);
            } else {
                removeComponent(TestComponentIds.Interactive);
            }
        }
        return this;
    }

    public boolean isPlayer() {
        return hasComponent(TestComponentIds.Player);
    }

    public Test2Entity setPlayer(boolean value) {
        if (value != hasComponent(TestComponentIds.Player)) {
            if (value) {
                addComponent(TestComponentIds.Player, PlayerComponent);
            } else {
                removeComponent(TestComponentIds.Player);
            }
        }
        return this;
    }
}
