package com.tenio.entitas.utils;

import com.tenio.engine.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
@SuppressWarnings({ "rawtypes", "unchecked" })
public class TestMatcher {

	private static Matcher _matcherInteractive;
	private static Matcher _matcherMotion;
	private static Matcher _matcherPlayer;
	private static Matcher _matcherPosition;
	private static Matcher _matcherScore;
	private static Matcher _matcherView;

	public static Matcher Interactive() {
		if (_matcherInteractive == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.Interactive);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherInteractive = matcher;
		}
		return _matcherInteractive;
	}

	public static Matcher Motion() {
		if (_matcherMotion == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.Motion);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherMotion = matcher;
		}
		return _matcherMotion;
	}

	public static Matcher Player() {
		if (_matcherPlayer == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.Player);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherPlayer = matcher;
		}
		return _matcherPlayer;
	}

	public static Matcher Position() {
		if (_matcherPosition == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.Position);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherPosition = matcher;
		}
		return _matcherPosition;
	}

	public static Matcher Score() {
		if (_matcherScore == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.Score);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherScore = matcher;
		}
		return _matcherScore;
	}

	public static Matcher View() {
		if (_matcherView == null) {
			var matcher = (Matcher) Matcher.allof(TestComponentIds.View);
			matcher.componentNames = TestComponentIds.componentNames();
			_matcherView = matcher;
		}
		return _matcherView;
	}
}
