package com.tenio.entitas.utils;

import com.tenio.entitas.components.Interactive;
import com.tenio.entitas.components.Motion;
import com.tenio.entitas.components.Player;
import com.tenio.entitas.components.Position;
import com.tenio.entitas.components.Score;
import com.tenio.entitas.components.View;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class TestComponentIds {

	public static final int Interactive = 0;
	public static final int Motion = 1;
	public static final int Player = 2;
	public static final int Position = 3;
	public static final int Score = 4;
	public static final int View = 5;
	public static final int totalComponents = 6;

	public static String[] componentNames() {
		return new String[] { "Interactive", "Motion", "Player", "Position", "Score", "View" };
	}

	@SuppressWarnings("rawtypes")
	public static Class[] componentTypes() {
		return new Class[] { Interactive.class, Motion.class, Player.class, Position.class, Score.class, View.class };
	}
}
