package com.tenio.entitas.utils;

import com.tenio.entitas.components.Interactive;
import com.tenio.entitas.components.Player;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
public class Test2ComponentIds {

	public static final int Interactive = 0;
	public static final int Player = 2;
	public static final int totalComponents = 2;

	public static String[] componentNames() {
		return new String[] { "Interactive", null, "Player", null, null, null };
	}

	@SuppressWarnings("rawtypes")
	public static Class[] componentTypes() {
		return new Class[] { Interactive.class, null, Player.class, null, null, null };
	}
}
