package com.tenio.entitas.utils;

import com.tenio.engine.entitas.matcher.Matcher;

/**
 * ---------------------------------------------------------------------------
 * '<auto-generated>' This code was generated by CodeGeneratorApp.
 * ---------------------------------------------------------------------------
 */
@SuppressWarnings({ "rawtypes", "unchecked" })
public class Test2Matcher {

	private static Matcher _matcherInteractive;
	private static Matcher _matcherPlayer;

	public static Matcher Interactive() {
		if (_matcherInteractive == null) {
			var matcher = (Matcher) Matcher.allof(Test2ComponentIds.Interactive);
			matcher.componentNames = Test2ComponentIds.componentNames();
			_matcherInteractive = matcher;
		}
		return _matcherInteractive;
	}

	public static Matcher Player() {
		if (_matcherPlayer == null) {
			var matcher = (Matcher) Matcher.allof(Test2ComponentIds.Player);
			matcher.componentNames = Test2ComponentIds.componentNames();
			_matcherPlayer = matcher;
		}
		return _matcherPlayer;
	}
}
